# Generated by Django 5.0.3 on 2024-03-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Produtc",
            new_name="Product",
        ),
    ]
